import type { Metadata } from "next";
import { Inter, Scheherazade_New, Noto_Sans_Arabic } from "next/font/google";
import "./globals.css";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const scheherazadeNew = Scheherazade_New({
  subsets: ["arabic"],
  variable: "--font-arabic-traditional",
  weight: "400"
});

const notoSans = Noto_Sans_Arabic({
  subsets: ["arabic"],
  variable: "--font-sans",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} ${scheherazadeNew.variable} ${notoSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
